name: Build AFK-WoW-Leveling with Ant

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: 16
          distribution: 'adopt'
          
      - name: Install Ant
        run: sudo apt-get install ant

      - name: Build with Ant
        run: ant jar

      - name: Upload JAR file
        uses: actions/upload-artifact@v2
        with:
          name: TrainerBattleBot
          path: jar/TrainerBattleBot.jar
          
      - name: Zip additional files
        run: zip -r additional-files.zip Pet\ Battles/ keybinds.txt README.md
          
      - name: Upload zip file
        uses: actions/upload-artifact@v2
        with:
          name: AdditionalFiles
          path: additional-files.zip