name: Build TrainerBattleBot

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Java 16
        uses: actions/setup-java@v2
        with:
          java-version: 16
          distribution: 'adopt'
          
      - name: Set up Ant
        run: sudo apt-get install ant
          
      - name: Build
        run: ant jar
          
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: TrainerBattleBot.jar
          path: jar/TrainerBattleBot.jar
