name: Build Windows Executable
on:
  push:
    branches:
      - dev-build
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Install JDK
        uses: actions/setup-java@v2
        with:
          java-version: '16'
      - name: Install AutoHotkey v2
        run: |
          wget https://www.autohotkey.com/download/ahk2.zip
          Expand-Archive -Path .\ahk2.zip -DestinationPath $env:ProgramFiles\AutoHotkey\v2 -Force
          Remove-Item -Path .\ahk2.zip -Force
      - name: Install AutoHotkeySC.bin
        run: |
          wget https://github.com/Lexikos/AutoHotkey_L/releases/download/v1.1.34.09/AutoHotkeySC.bin
          Move-Item -Path .\AutoHotkeySC.bin -Destination $env:ProgramFiles\AutoHotkey\v2 -Force
      - name: Install AHK2exe
        run: |
          wget https://github.com/ahkscript/ahk2exe/releases/download/v1.1.34.09/ahk2exe_v1.1.34.09.zip
          Expand-Archive -Path .\ahk2exe_v1.1.34.09.zip -DestinationPath $env:ProgramFiles\AutoHotkey\v2 -Force
          Remove-Item -Path .\ahk2exe_v1.1.34.09.zip -Force
      - name: Build TrainerBattleBot
        run: |
          cd Trainer\ Battles
          $env:PATH += ";$env:ProgramFiles\AutoHotkey\v2"
          & "$env:ProgramFiles\AutoHotkey\v2\Compiler\Ahk2Exe.exe" /in TrainerBattleBot.ahk /bin TrainerBattleBot.exe /icon TrainerBattleBot.ico /mpress 2
      - name: Upload TrainerBattleBot Executable
        uses: actions/upload-artifact@v2
        with:
          name: TrainerBattleBot Executable
          path: Trainer\ Battles\TrainerBattleBot.exe
