name: Build

on:
  push:
    branches:
      - dev-build

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11

    - name: Build with Gradle
      run: ./gradlew shadowJar
